plugins {
    id 'java'
    id 'application'
}

group = 'ru.bookapp'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

// Версии зависимостей
ext {
    springVersion = '7.0.8'
    testcontainersVersion = '1.20.1'
    junitJupiterVersion = '6.1.3'
    mockitoVersion = '5.23.0'
    hibernateVersion = '7.1.0.Final'
}

dependencies {
    // Spring Data JPA сам подтянет context, jdbc и tx версии 7.0.8
    implementation "org.springframework.data:spring-data-jpa:4.1.0"

    // PostgreSQL Driver
    implementation 'org.postgresql:postgresql:42.7.11'

    // Hibernate (JPA)
    implementation "org.hibernate.orm:hibernate-core:$hibernateVersion"

    // Test Dependencies
    // JUnit (Оставляем только один агрегатор, он сам все подтянет)
    testImplementation "org.junit.jupiter:junit-jupiter:$junitJupiterVersion"

    //    Spring Test
    testImplementation "org.springframework:spring-test:$springVersion"

    //    Mockito для JUnit 5
    testImplementation "org.mockito:mockito-core:$mockitoVersion"
    testImplementation "org.mockito:mockito-junit-jupiter:$mockitoVersion"

    //    Testcontainers
    testImplementation "org.testcontainers:testcontainers:$testcontainersVersion"
    testImplementation "org.testcontainers:postgresql:$testcontainersVersion"
    testImplementation "org.testcontainers:junit-jupiter:$testcontainersVersion"

    // Дополнительные зависимости для Testcontainers
    testImplementation "org.slf4j:slf4j-simple:2.0.9"

}

application {
    mainClass = 'ru.bookapp.Main'
}

test {
    useJUnitPlatform()
}