plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework:spring-context:7.0.8'
    implementation 'org.springframework:spring-context:7.0.8'
    implementation 'org.springframework:spring-jdbc:7.0.8'
    implementation("org.postgresql:postgresql:42.7.11")
    implementation 'org.slf4j:slf4j-simple:2.0.9'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}